# Generated by Django 3.0.5 on 2020-04-07 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babies_api', '0002_baby_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='baby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='babies_api.Baby'),
        ),
    ]
